version: "3"

services:
  # Used to emulate amazon SQS

  # localstack:
  #   image: localstack/localstack
  #   ports:
  #     - "4566:4566"
  #     - "4571:4571"
  #     - "${PORT_WEB_UI-8085}:${PORT_WEB_UI-8080}"
  #   environment:
  #     - SERVICES=sqs
  #     - DEBUG=${DEBUG- }
  #     - DATA_DIR=${DATA_DIR- }
  #     - PORT_WEB_UI=${PORT_WEB_UI- }
  #     - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
  #     - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #   volumes:
  #     - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3308:3306"

  events:
    build: docker/php
    depends_on: [mysql]
    volumes: [./events:/app]
    ports: [8000:80]

  workflows:
    build: docker/php
    depends_on: [mysql]
    volumes: [./workflows:/app]
    ports: [8001:80]

volumes:
  database: